fix(ui): Double clicking controls no longer enters fullscreen
meisterplayer/ui-standardui pull request #14
Opened 2017-06-16 15:52 UTC by Thomasvdam

Also works for double taps.

Closes meisterplayer/meisterplayer#43

2017-06-19 06:30 UTC, FranklinWaller approved these changes

2017-06-20 08:36 UTC, buttonfreak commented on src/js/bottom/BottomBar.js
> +        this.element.addEventListener('touchstart', this.stopPointerPropagation);
Shouldn't these bind to this ? Or enclose in an arrowmethod?

2017-06-20 08:38 UTC, FranklinWaller commented on src/js/bottom/BottomBar.js
> +        this.element.addEventListener('touchstart', this.stopPointerPropagation);
It doesn't use 'this' in stopPointerPropagation but i agree to keep consistency (Plus it's part of the same class) it should bind to this

2017-06-20 08:41 UTC, ivo-toby requested changes
Bind callbacks to this or wrap callbacks into arrow function

2017-06-23 12:32 UTC, Thomasvdam commented
Bound the callbacks, good catch!

2017-06-26 13:48 UTC, ivo-toby approved these changes

2017-06-26 13:48 UTC, merged